version: '3.8'

services:
  # Local PostgreSQL database for development
  postgres-dev:
    image: postgres:15-alpine
    container_name: opsbrain-postgres-dev
    environment:
      POSTGRES_DB: opsbrain_dev
      POSTGRES_USER: opsbrain_user
      POSTGRES_PASSWORD: dev_password_123
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U opsbrain_user -d opsbrain_dev"]
      interval: 10s
      timeout: 5s
      retries: 5
    profiles:
      - dev
      - full

  # Optional: pgAdmin for database management
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: opsbrain-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@opsbrain.dev
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres-dev
    profiles:
      - tools
      - full

  opsbrain:
    build: .
    ports:
      - "8000:8000"
    environment:
      # Required environment variables - set these in your .env file or environment
      - SLACK_BOT_TOKEN=${SLACK_BOT_TOKEN}
      - SLACK_SIGNING_SECRET=${SLACK_SIGNING_SECRET}
      - NOTION_API_KEY=${NOTION_API_KEY}
      - NOTION_DB_ID=${NOTION_DB_ID}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      
      # Optional database IDs for enhanced features
      - NOTION_GOALS_DB_ID=${NOTION_GOALS_DB_ID:-}
      - NOTION_CLIENTS_DB_ID=${NOTION_CLIENTS_DB_ID:-}
      - NOTION_PROJECTS_DB_ID=${NOTION_PROJECTS_DB_ID:-}
      - NOTION_METRICS_DB_ID=${NOTION_METRICS_DB_ID:-}
      
      # Database configuration - use PostgreSQL in all environments
      - DATABASE_URL=${DATABASE_URL:-postgresql://opsbrain_user:dev_password_123@postgres-dev:5432/opsbrain_dev}
      
      # Production settings
      - TEST_MODE=${TEST_MODE:-false}
    depends_on:
      - postgres-dev
    restart: unless-stopped
    profiles:
      - dev
      - full
      - default
    
    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  postgres_dev_data:
